### ISSUE TITLE
Configure the DEFAULT_AUTO_FIELD setting

### ISSUE THREAD

**Issue by chaalelidris** [OtchereDev/django_netflix_clone#6]
core.CustomUser: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the CoreConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

**Comment by OtchereDev** [comment]
DEFAULT_AUTO_FIELD='django.db.models.BigAutoField' 

add this to the last line of your settings.py
